name: Deploy Unitask

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: mbstring, pdo, pdo_mysql, bcmath, intl

      - name: Install PHP dependencies
        run: |
          composer install \
            --no-dev \
            --optimize-autoloader \
            --no-interaction

      - name: Prepare build folder
        run: |
          mkdir -p build

          rsync -av \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "tests" \
            ./ build/

      - name: Copy vendor into build (important step)
        run: |
          cp -R vendor build/vendor

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -p ${{ secrets.VPS_SSH_PORT }} \
            ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to VPS
        run: |
          cp docker-compose.yml.prod.example build/docker-compose.yml
          rsync -rlvz \
            --no-times \
            --no-perms \
            --no-owner \
            --no-group \
            --exclude ".env" \
            --exclude "storage/" \
            --exclude "bootstrap/cache/" \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.VPS_SSH_PORT }}" \
            build/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/srv/apps/unitask

      - name: Remote deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.VPS_SSH_PORT }} \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

          set -euxo pipefail

          cd /srv/apps/unitask

          echo "Garantindo .env..."
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

          echo "Subindo containers..."
          docker compose down --remove-orphans
          docker compose up -d --build

          echo "Rodando migrations..."
          docker compose exec -T unitask php artisan optimize:clear || true
          docker compose exec -T unitask php artisan migrate --force || true

          EOF

      - name: Cleanup
        run: rm -f ~/.ssh/id_ed25519